apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rag-secrets-ext
  namespace: rag-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: rag-secrets
    creationPolicy: Owner
  data:
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: rag-openai-key
  - secretKey: JWT_PUBLIC_KEY
    remoteRef:
      key: rag-jwt-public-key
  - secretKey: POSTGRES_URL
    remoteRef:
      key: rag-postgres-url
